Repository Rdatatable/data.table, pull requests merged in 2019-05, with the labels that each got.

#2656 csvy reading capabilities
  DESCRIPTION
  NEWS.md
  R/fread.R
  appveyor.yml
  inst/tests/csvy/test.csvy
  inst/tests/csvy/test_attributes.csvy
  inst/tests/csvy/test_comment.csvy
  inst/tests/csvy/test_extraneous.csvy
  inst/tests/csvy/test_incomplete_header.csvy
  inst/tests/csvy/test_missing_type.csvy
  inst/tests/csvy/test_override_dec.csvy
  inst/tests/csvy/test_override_header.csvy
  inst/tests/csvy/test_override_na.csvy
  inst/tests/csvy/test_override_quote.csvy
  inst/tests/csvy/test_override_sep.csvy
  inst/tests/csvy/test_skip.csvy
  inst/tests/tests.Rraw
  man/fread.Rd
Labels: Enhancement, fread

#3556 test numbers in increasing order
  R/test.data.table.R
  inst/tests/tests.Rraw
Labels: internals

#3566 utils.R coverage
  NAMESPACE
  R/fread.R
  R/print.data.table.R
  R/setkey.R
  R/utils.R
  inst/tests/tests.Rraw
Labels: internals

#3572 New vignette -- Usages of .SD
  NEWS.md
  vignettes/Pitching.RData
  vignettes/Teams.RData
  vignettes/datatable-sd-usage.Rmd
  vignettes/plots/grouping_illustration.png
Labels: documentation
