Repository Rdatatable/data.table, pull requests merged in 2019-12, with the labels that each got.

#4050 Translation shawn
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#3989 Translation yilei
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4106 output platform details when tests fail
  R/test.data.table.R
Labels: internals

#3987 Translation to zh_CN assigned to group 12
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#3990 Translation fengqifang
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4069 done some translation
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#3997 Translation to zh_CN assigned to group 4
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4051 My part of translation has been completed. It's so happy!
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4055 Translation yuliang li
  po/zh_CN.po
Labels: translation

#4049 Translation to zh_CN - Group 17
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4054 Translation yc0802
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/zh_CN.po
Labels: translation

#4046 done some translation!-kingda
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4146 Translation leftover pt2
  R/data.table.R
  R/devel.R
  R/last.R
  R/setkey.R
  R/test.data.table.R
  inst/po/en@quot/LC_MESSAGES/R-data.table.mo
  inst/po/en@quot/LC_MESSAGES/data.table.mo
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  inst/tests/tests.Rraw
  po/R-data.table.pot
  po/R-zh_CN.po
  po/data.table.pot
  po/zh_CN.po
  src/fread.c
  src/gsumm.c
Labels: translation

#3935 Add Chinese error message translations
  .dev/CRAN_Release.cmd
  R/between.R
  R/data.table.R
  R/devel.R
  R/groupingsets.R
  R/last.R
  R/onAttach.R
  R/setkey.R
  R/test.data.table.R
  inst/po/en@quot/LC_MESSAGES/R-data.table.mo
  inst/po/en@quot/LC_MESSAGES/data.table.mo
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  inst/tests/tests.Rraw
  man/melt.data.table.Rd
  po/R-data.table.pot
  po/R-zh_CN.po
  po/data.table.pot
  po/zh_CN.po
  src/assign.c
  src/between.c
  src/bmerge.c
  src/chmatch.c
  src/cj.c
  src/coalesce.c
  src/data.table.h
  src/dogroups.c
  src/fastmean.c
  src/fcast.c
  src/fifelse.c
  src/fmelt.c
  src/forder.c
  src/frank.c
  src/fread.c
  src/freadR.c
  src/freadR.h
  src/froll.c
  src/frollR.c
  src/frolladaptive.c
  src/fsort.c
  src/fwrite.c
  src/fwrite.h
  src/fwriteR.c
  src/gsumm.c
  src/ijoin.c
  src/init.c
  src/inrange.c
  src/nafill.c
  src/openmp-utils.c
  src/po.h
  src/rbindlist.c
  src/reorder.c
  src/shift.c
  src/subset.c
  src/transpose.c
  src/types.c
  src/uniqlist.c
  src/utils.c
  src/vecseq.c
  src/wrappers.c
Labels: translation

#4137 use 4.0 paths for R-devel
  .gitlab-ci.yml
Labels: ci

#4149 add NEWS item for translation
  NEWS.md
  R/onAttach.R
  inst/po/en@quot/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  po/R-data.table.pot
  po/R-zh_CN.po
Labels: translation
