Repository Rdatatable/data.table, pull requests merged in 2019-11, with the labels that each got.

#4011 fix Rd warnings
  .dev/CRAN_Release.cmd
  NEWS.md
  man/fread.Rd
  man/like.Rd
  man/openmp-utils.Rd
Labels: documentation

#3985 Translation to zh_CN assigned to group 3
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4002 Translation haogao gu
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4023 Translation finished (soappp)
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#3995 Finish translation to zh_CN assigned to group 5 (Leo Lee)
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4034 Translation dracodoc
  inst/po/en@quot/LC_MESSAGES/data.table.mo
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/R-zh_CN.po
  po/data.table.pot
  po/zh_CN.po
  src/fread.c
  src/po.h
Labels: translation

#4039 Translation caiquanyou
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4010 translation(partial) into zh_CN by Yuanchen Xie
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4064 Windows warnings with gcc about %lld
  .dev/CRAN_Release.cmd
  NEWS.md
  src/assign.c
  src/between.c
  src/chmatch.c
  src/data.table.h
  src/fifelse.c
  src/forder.c
  src/fread.c
  src/fread.h
  src/freadR.c
  src/froll.c
  src/frolladaptive.c
  src/fsort.c
  src/fwrite.c
  src/init.c
  src/rbindlist.c
  src/uniqlist.c
Labels: internals
