Repository Rdatatable/data.table, pull requests merged in 2019-09, with the labels that each got.

#3600 frollapply
  NAMESPACE
  NEWS.md
  R/froll.R
  inst/tests/froll.Rraw
  man/froll.Rd
  src/data.table.h
  src/froll.c
  src/frollR.c
  src/init.c
Labels: High

#3818 use .datatable.aware when data.table in Sugggests
  vignettes/datatable-importing.Rmd
Labels: documentation

#3850 chmatchdup() now handles non-ascii strings consistently
  inst/tests/tests.Rraw
  src/chmatch.c
  src/data.table.h
  src/utils.c
Labels: encoding

#3849 setnames() should treat different Encoding as non-equal strings
  R/data.table.R
  inst/tests/tests.Rraw
Labels: encoding

#3878 LTO compilation flag, also strict compilation warning check
  .gitlab-ci.yml
Labels: ci

#3880 flto gcc flag only for data.table
  .gitlab-ci.yml
Labels: ci

#3677 A pkgdown website for data.table
  .Rbuildignore
  .gitlab-ci.yml
  DESCRIPTION
  NEWS.0.md
  NEWS.md
  README.md
  _pkgdown.yml
  cheatsheet.png
  logo.png
  man/set2key.Rd
  man/transform.data.table.Rd
  vignettes/datatable-importing.Rmd
  vignettes/datatable-sd-usage.Rmd
Labels: High, www

#3898 extra rbindlist test
  inst/tests/tests.Rraw
  src/rbindlist.c
Labels: dev
