Repository Rdatatable/data.table, pull requests merged in 2019-03, with the labels that each got.

#3470 chmatchdup when table unique
  inst/tests/tests.Rraw
  src/chmatch.c
Labels: dev, internals

#3478 error downgraded to warning
  R/data.table.R
  inst/tests/tests.Rraw
Labels: dev

#3486 Widen TOC for the FAQ vignette.
  vignettes/datatable-faq.Rmd
Labels: documentation
