Repository Rdatatable/data.table, pull requests merged in 2020-05, with the labels that each got.

#4431 upgrade CI to R 4.0
  .gitattributes
  .gitlab-ci.yml
Labels: ci

#4428 fixes R-devel foverlaps failures due to c.POSIXct change
  NEWS.md
  R/foverlaps.R
Labels: R-devel

#4465 Remove 'typedef R_xlen_t RLEN' in data.table.h
  src/data.table.h
Labels: internals

#4492 relaxed test 1590 given change in R-devel on ordering encodings
  inst/tests/tests.Rraw
Labels: encoding, internals, platform-specific

#4494 further relaxation to test 1590 given change in R-devel on ordering encodings
  inst/tests/tests.Rraw
Labels: dev, platform-specific
