Repository Rdatatable/data.table, pull requests merged in 2020-06, with the labels that each got.

#4518 bmerge.c compile warning in dev
  src/bmerge.c
Labels: dev

#4537 fixed iSD recycle when empty, and added test
  R/data.table.R
  inst/tests/tests.Rraw
  src/dogroups.c
Labels: dev

#4484 throttle threads for iterated small data tasks
  NEWS.md
  R/openmp-utils.R
  inst/tests/tests.Rraw
  man/openmp-utils.Rd
  src/between.c
  src/cj.c
  src/coalesce.c
  src/data.table.h
  src/fifelse.c
  src/forder.c
  src/froll.c
  src/frollR.c
  src/frolladaptive.c
  src/fsort.c
  src/gsumm.c
  src/nafill.c
  src/openmp-utils.c
  src/reorder.c
  src/subset.c
  src/types.c
Labels: High

#4556 fix current win failures
  .gitlab-ci.yml
Labels: High

#4559 proper link
  .gitlab-ci.yml
Labels: High

#4548 no need re-order for equi join
  R/data.table.R
  inst/tests/tests.Rraw
Labels: joins

#4584 R-devel check detects soft issues now
  .ci/README.md
  .gitlab-ci.yml
Labels: ci
