Repository Rdatatable/data.table, pull requests merged in 2020-12, with the labels that each got.

#4835 cater for latest change in R-devel today which breaks test 2022
  .dev/CRAN_Release.cmd
  R/test.data.table.R
Labels: R-devel

#4840 follow up #4835 another change in R-devel
  R/test.data.table.R
Labels: R-devel

#4297 should use the long int 2 to avoid integer overflow
  NEWS.md
  src/gsumm.c
Labels: GForce, High

#4850 extra print in test summary
  R/test.data.table.R
  inst/tests/tests.Rraw
Labels: High, tests
