Repository Rdatatable/data.table, pull requests merged in 2021-08, with the labels that each got.

#5087 fixing "invalid permission" segfault from #5077 by only starting the amount of thread, memory was allocated for.
  DESCRIPTION
  NEWS.md
  inst/tests/tests.Rraw
  src/forder.c
Labels: bug

#4713 Use metaprogramming instead of parse to build bysub
  R/data.table.R
  inst/tests/tests.Rraw
Labels: internals

#5109 Gforce edge case creates segfault
  NEWS.md
  R/test.data.table.R
  inst/tests/tests.Rraw
  src/gsumm.c
Labels: bug, segfault, GForce

#5089 added ghead/gtail support for n>1
  NEWS.md
  R/data.table.R
  inst/tests/tests.Rraw
  src/gsumm.c
Labels: feature request, GForce
