Repository Rdatatable/data.table, pull requests merged in 2021-05, with the labels that each got.

#4937 improve error message
  R/data.table.R
Labels: documentation

#4929 Use brackify more to replace paste(collapse=',')
  R/data.table.R
  R/fcast.R
  R/print.data.table.R
  R/setops.R
  R/test.data.table.R
  R/utils.R
  inst/tests/tests.Rraw
Labels: internals

#4928 Use scalar logical operators where appropriate
  R/as.data.table.R
  R/data.table.R
  R/merge.R
  R/setkey.R
  inst/tests/tests.Rraw
Labels: internals

#4927 use paste0 in vignette
  vignettes/datatable-reshape.Rmd
Labels: documentation

#4926 use encodeString over gsub("\n", "\\\\n")
  R/test.data.table.R
Labels: internals

#4925 remove tab (\t) from source
  vignettes/datatable-reference-semantics.Rmd
Labels: documentation, internals

#4836 extra test to ensure behavior will not silently change in future
  inst/tests/tests.Rraw
Labels: tests

#4859 sync data.table.h signature of forder with that in forder.c
  src/data.table.h
Labels: High

#4723 fix variable with melt(measure.vars=list), na.rm=T/F consistency
  NEWS.md
  inst/tests/tests.Rraw
  man/melt.data.table.Rd
  src/fmelt.c
Labels: High, consistency, reshape

#4720 support missing values in measure.vars arg to melt
  NEWS.md
  inst/tests/tests.Rraw
  man/melt.data.table.Rd
  src/chmatch.c
  src/fmelt.c
Labels: reshape

#4731 melt with custom variable columns using variable_table attribute
  .Rbuildignore
  NEWS.md
  R/data.table.R
  R/fmelt.R
  R/utils.R
  inst/tests/tests.Rraw
  man/measure.Rd
  man/melt.data.table.Rd
  src/data.table.h
  src/fmelt.c
  src/init.c
  vignettes/datatable-reshape.Rmd
Labels: reshape

#4737 fix for melt with na.rm=TRUE and list column value
  inst/tests/tests.Rraw
  src/fmelt.c
Labels: consistency, reshape

#4151 More translations: cat() output
  R/between.R
  R/bmerge.R
  R/cedta.R
  R/data.table.R
  R/devel.R
  R/fmelt.R
  R/foverlaps.R
  R/fread.R
  R/fwrite.R
  R/last.R
  R/print.data.table.R
  R/setkey.R
  R/tables.R
  R/test.data.table.R
  R/utils.R
  inst/tests/tests.Rraw
  po/R-data.table.pot
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4304 programming on data.table
  .Rbuildignore
  NAMESPACE
  NEWS.md
  R/data.table.R
  R/programming.R
  R/test.data.table.R
  inst/tests/programming.Rraw
  man/data.table.Rd
  man/substitute2.Rd
  src/data.table.h
  src/init.c
  src/programming.c
  tests/programming.R
  vignettes/datatable-programming.Rmd
Labels: High

#4811 get Rraw files to highlight well on GitHub
  .gitattributes
Labels: dev

#4806 testing is more robust to changes in base messages
  R/test.data.table.R
  inst/tests/tests.Rraw
Labels: internals

#4269 & --> && where appropriate, and some tidying of tests/CRAN_release
  .dev/CRAN_Release.cmd
  R/between.R
  R/data.table.R
  R/merge.R
  inst/tests/other.Rraw
  inst/tests/tests.Rraw
Labels: internals

#4990 .checkTypos drops dependency on English locale
  NEWS.md
  R/data.table.R
Labels: translation

#4847 Bug fix for gmin and blank strings
  DESCRIPTION
  NEWS.md
  inst/tests/tests.Rraw
  src/data.table.h
  src/gsumm.c
  src/init.c
Labels: GForce

#5000 Localize remaining loop variables
  src/assign.c
  src/dogroups.c
  src/fastmean.c
  src/fcast.c
  src/frank.c
  src/gsumm.c
  src/ijoin.c
  src/inrange.c
Labels: internals

#5015 Use anyDuplicated as appropriate
  R/data.table.R
  R/fmelt.R
Labels: internals

#5016 combine consecutive stopifnot calls
  R/fread.R
Labels: internals

#5017 Flip any(!x) to !all(x) and all(!x) to !any(x)
  R/as.data.table.R
  R/data.table.R
  R/xts.R
Labels: internals

#5021 detect a function-cum-column in i
  NEWS.md
  R/data.table.R
  inst/tests/tests.Rraw
Labels: translation

#5010 programming vignette tweak
  _pkgdown.yml
  vignettes/datatable-programming.Rmd
Labels: documentation
