Repository Rdatatable/data.table, pull requests merged in 2021-07, with the labels that each got.

#5056 Add new template functions for internal error/warning/message to ease translation
  .gitignore
  R/as.data.table.R
  R/between.R
  R/bmerge.R
  R/data.table.R
  R/devel.R
  R/fcast.R
  R/fmelt.R
  R/foverlaps.R
  R/fread.R
  R/fwrite.R
  R/groupingsets.R
  R/last.R
  R/merge.R
  R/onAttach.R
  R/onLoad.R
  R/openmp-utils.R
  R/print.data.table.R
  R/programming.R
  R/setkey.R
  R/setops.R
  R/tables.R
  R/test.data.table.R
  R/translation.R
  R/transpose.R
  R/utils.R
  R/xts.R
  inst/tests/programming.Rraw
  inst/tests/tests.Rraw
Labels: translation

#5068 fully migrate to templated messages
  R/AllS4.R
  R/IDateTime.R
  R/as.data.table.R
  R/between.R
  R/bmerge.R
  R/data.table.R
  R/duplicated.R
  R/fcast.R
  R/fmelt.R
  R/foverlaps.R
  R/frank.R
  R/fread.R
  R/fwrite.R
  R/groupingsets.R
  R/merge.R
  R/onAttach.R
  R/onLoad.R
  R/openmp-utils.R
  R/print.data.table.R
  R/programming.R
  R/setkey.R
  R/setops.R
  R/test.data.table.R
  R/timetaken.R
  R/transpose.R
  R/uniqlist.R
  R/utils.R
  R/xts.R
  inst/tests/tests.Rraw
Labels: translation

#5058 proper handling list-like objects in env arg #5057
  R/programming.R
  inst/tests/programming.Rraw
Labels: dev

#5072 Set default domain="R-data.table" explicitly for translation functions
  R/onAttach.R
  R/onLoad.R
  R/translation.R
Labels: translation

#5053 melt(na.rm=TRUE) should remove rows with missing list column
  NEWS.md
  inst/tests/tests.Rraw
  man/melt.data.table.Rd
  src/assign.c
  src/data.table.h
  src/dogroups.c
  src/fmelt.c
  src/rbindlist.c
Labels: consistency, reshape

#4893 setDF deletes the index attribute
  NEWS.md
  R/data.table.R
  inst/tests/tests.Rraw
  man/setDF.Rd
  src/utils.c
Labels: High, bug
