Repository Rdatatable/data.table, pull requests merged in 2021-06, with the labels that each got.

#5038 Remove domain= usage in setops.R
  R/setops.R
Labels: translation

#4502 some sapply->vapply replacements
  R/as.data.table.R
  R/cedta.R
  R/data.table.R
  R/fread.R
  R/groupingsets.R
  R/setkey.R
  R/utils.R
Labels: internals

#4506 catch some partial matching issues in examples
  .dev/CRAN_Release.cmd
  man/address.Rd
  man/dcast.data.table.Rd
  man/deprecated.Rd
  man/melt.data.table.Rd
  man/openmp-utils.Rd
  man/shouldPrint.Rd
  man/test.data.table.Rd
Labels: documentation

#4462 convenience macros for char->digit in fread
  src/fread.c
Labels: internals

#4590 improve copy docs
  man/address.Rd
  man/copy.Rd
Labels: documentation

#4447 replace substring globally with substr
  .dev/CRAN_Release.cmd
  .dev/revdep.R
  R/data.table.R
  R/fread.R
  R/test.data.table.R
  R/utils.R
  inst/tests/benchmark.Rraw
  inst/tests/tests.Rraw
Labels: internals, performance

#5047 Don't call copyMostAttrib on ScalarLogical result
  src/assign.c
Labels: dev

#5050 simplify checking for untranslated messages
  .dev/CRAN_Release.cmd
  src/fwrite.c
  src/init.c
  src/nafill.c
  src/programming.c
  src/utils.c
Labels: translation

#4924 internal cleanup -- new helper clip_msec
  R/IDateTime.R
Labels: internals

#4408 Add . and .. aliases to ?data.table
  NEWS.md
  R/data.table.R
  man/data.table.Rd
  vignettes/datatable-faq.Rmd
Labels: documentation

#5054 remove allocNAVector in melt for memory efficiency
  NEWS.md
  src/fmelt.c
Labels: internals, performance, reshape
