Repository Rdatatable/data.table, pull requests merged in 2022-10, with the labels that each got.

#5476 gcc-12 always-false in fread.c
  .dev/CRAN_Release.cmd
  DESCRIPTION
  Makefile
  NEWS.md
  src/fread.c
  src/init.c
Labels: CRAN

#5477 pass -Wstrict-prototypes for CRAN
  .dev/cc.R
  NEWS.md
  src/assign.c
  src/data.table.h
  src/forder.c
  src/fread.c
  src/fwrite.c
  src/fwrite.h
  src/fwriteR.c
  src/gsumm.c
  src/init.c
  src/openmp-utils.c
  src/snprintf.c
  src/utils.c
Labels: CRAN

#5480 fwrite dateTimeAs='write.csv' test 1741 massaged to pass R-devel
  .dev/CRAN_Release.cmd
  NEWS.md
  inst/tests/tests.Rraw
Labels: R-devel

#5463 memrecycle no snprintf overhead
  NEWS.md
  src/assign.c
Labels: dev
