Repository Rdatatable/data.table, pull requests merged in 2022-11, with the labels that each got.

#5508 ensure that DCF does not have empty line at the end before appending …
  .gitlab-ci.yml
Labels: ci

#5515 test.data.table(memtest=TRUE)
  NEWS.md
  R/test.data.table.R
  inst/tests/tests.Rraw
  man/test.data.table.Rd
Labels: tests

#5518 Move suggests from tests.Rraw to other.Rraw
  inst/tests/other.Rraw
  inst/tests/tests.Rraw
Labels: tests

#5519 report elapsed time even if tests fail
  R/test.data.table.R
Labels: tests

#5524 tables(mb=type_size) faster lower bound MB by default
  NEWS.md
  R/tables.R
  man/tables.Rd
Labels: performance, tests

#5501 Limit deparse in name_dots to 1 line
  NEWS.md
  R/utils.R
  inst/tests/benchmark.Rraw
Labels: High
