Repository Rdatatable/data.table, pull requests merged in 2023-12, with the labels that each got.

#5468 rbindlist segfault for fill=TRUE and usenames=FALSE
  NEWS.md
  inst/tests/tests.Rraw
  src/rbindlist.c
Labels: segfault, dev

#5820 CI reporting improvements
  .ci/publish.R
  .gitlab-ci.yml
Labels: ci

#5561 add favicons to webpage
  .gitlab-ci.yml
  .graphics/favicon/apple-touch-icon-120x120.png
  .graphics/favicon/apple-touch-icon-152x152.png
  .graphics/favicon/apple-touch-icon-180x180.png
  .graphics/favicon/apple-touch-icon-60x60.png
  .graphics/favicon/apple-touch-icon-76x76.png
  .graphics/favicon/apple-touch-icon.png
  .graphics/favicon/favicon-16x16.png
  .graphics/favicon/favicon-32x32.png
  .graphics/favicon/favicon.ico
Labels: www

#5681 checkPoTools found bad translations
  po/R-zh_CN.po
Labels: translation

#5857 remove use of rbindlist(..., use.names=FALSE, fill=TRUE) in merge
  NEWS.md
  R/merge.R
  inst/tests/tests.Rraw
Labels: regression, dev, rbindlist

#5862 Update .pot & .po files
  po/R-data.table.pot
  po/R-zh_CN.po
  po/data.table.pot
  po/zh_CN.po
Labels: translation
