Repository Rdatatable/data.table, pull requests merged in 2024-07, with the labels that each got.

#6226 Update gist url
  R/IDateTime.R
  man/IDateTime.Rd
Labels: documentation

#6229 Force installing remotes
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6202 Update .pot files
  po/R-data.table.pot
  po/data.table.pot
Labels: translation

#6241 Set occasional suite to run again tomorrow
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6251 Try an explicit R_LIBS_USER to avoid losing packages between steps
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6250 Add .libPaths() to the test.data.table() diagnostic
  R/test.data.table.R
Labels: ci

#6260 Combine deps install step
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6267 Remove rraw from lint
  .github/workflows/lint.yaml
Labels: ci

#6268 build and check args consistently handled in occasional check
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6269 Pass TEST_DATA_TABLE_WITH_OTHER_PACKAGES more explicitly
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6278 Try R_LIBS_USER again in occasional check
  .github/workflows/R-CMD-check-occasional.yaml
  inst/tests/other.Rraw
Labels: ci

#6199 Add Brazilian Portuguese translation
  .dev/CRAN_Release.cmd
  NEWS.md
  po/R-pt_BR.po
  po/pt_BR.po
Labels: translation

#6292 Consistently set R_LIBS_USER across steps
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6274 Explicitly request -Wvla to prevent backsliding
  .gitlab-ci.yml
  src/forder.c
  src/fwrite.c
Labels: ci

#6281 Update Chinese translations for release
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4386 Teach forder to re-use existing key and index attributes instead of sorting from scratch
  NEWS.md
  R/bmerge.R
  R/data.table.R
  R/setkey.R
  inst/tests/tests.Rraw
  src/bmerge.c
  src/data.table.h
  src/forder.c
  src/init.c
Labels: High

#6002 Remove exported [.data.table
  NAMESPACE
  NEWS.md
  inst/tests/tests.Rraw
Labels: breaking-change
