Repository Rdatatable/data.table, pull requests merged in 2024-04, with the labels that each got.

#6022 Restore GHA on Windows
  .Rbuildignore
  .appveyor.yml
  .ci/README.md
  .github/workflows/R-CMD-check.yaml
  README.md
  inst/tests/benchmark.Rraw
  inst/tests/tests.Rraw
  src/snprintf.c
Labels: ci

#6029 Make tests robust to exact phrasing & language of base condition messages
  R/test.data.table.R
  inst/tests/tests.Rraw
Labels: tests, translation

#5663 Convenience features for .SDcols patterns perl=TRUE
  NEWS.md
  R/fmelt.R
  inst/tests/tests.Rraw
  man/data.table.Rd
  man/patterns.Rd
Labels: reshape

#5247 melt(measure.vars=list) returns indices in variable column
  NEWS.md
  R/data.table.R
  R/fmelt.R
  inst/tests/tests.Rraw
  src/fmelt.c
Labels: consistency, reshape

#6041 Changes to ensure test(number instead of test(name
  inst/tests/tests.Rraw
Labels: tests

#6081 Spell out "significant figures" in ?setNumericRounding
  man/setNumericRounding.Rd
Labels: documentation

#6088 Use options= to avoid failing to reset verbose
  inst/tests/tests.Rraw
Labels: tests
