Repository Rdatatable/data.table, pull requests merged in 2024-09, with the labels that each got.

#6450 errant ')' in msgfmt_linter
  .ci/linters/po/msgfmt_linter.R
Labels: ci

#6467 Initialize more variables
  src/fifelse.c
  src/frollR.c
  src/idatetime.c
  src/nafill.c
Labels: internals

#6481 Only run atime tests on non-fork branches
  .github/workflows/performance-tests.yml
Labels: ci, atime

#6475 Use dngettext() for some plural messages in C
  inst/tests/tests.Rraw
  src/assign.c
  src/fread.c
  src/fwrite.c
  src/nafill.c
  src/po.h
  src/rbindlist.c
  src/utils.c
Labels: translation

#6477 Print \n separately to unify messages in by= showProgress conclusion
  src/dogroups.c
Labels: translation

#6451 Fix fcase() segfault (#6452)
  NEWS.md
  inst/tests/tests.Rraw
  src/fifelse.c
Labels: internals

#6483 Refactor copyFile() message fragment for ease of translation
  inst/tests/tests.Rraw
  src/fread.c
Labels: translation

#6476 Use ngettext() for some plural messages in R
  R/bmerge.R
  R/data.table.R
  R/fcast.R
  R/fmelt.R
  R/foverlaps.R
  R/fread.R
  R/merge.R
  R/print.data.table.R
  R/setops.R
  R/test.data.table.R
  R/utils.R
  inst/tests/tests.Rraw
Labels: translation

#6489 Remove targetDesc helper in assign.c in favor of splitting cases for i18n
  inst/tests/tests.Rraw
  src/assign.c
Labels: translation

#6506 wrong ')' placement
  .ci/linters/po/msgfmt_linter.R
Labels: ci

#6504 Message fixes for the C code
  src/fmelt.c
  src/fread.c
  src/fsort.c
  src/gsumm.c
  src/init.c
Labels: translation

#6518 skip check of .po agreeing with .mo
  .ci/linters/po/msgfmt_linter.R
Labels: ci, translation

#6469 French translation (po files)
  inst/po/fr/LC_MESSAGES/R-data.table.mo
  inst/po/fr/LC_MESSAGES/data.table.mo
  po/R-fr.po
  po/fr.po
Labels: translation

#6485 Add performance regression test for fread Date coercion
  .ci/atime/tests.R
Labels: atime

#6534 Refactor internal helpers which generate fragmented messages
  R/fmelt.R
  R/utils.R
  inst/tests/tests.Rraw
  man/measure.Rd
Labels: translation

#6530 Refactor CHECK_RANGE to be i18n friendly
  src/assign.c
Labels: translation

#6539 Add notranslate for untranslateable fragments
  src/assign.c
  src/bmerge.c
  src/dogroups.c
  src/forder.c
  src/fread.c
  src/freadR.c
  src/fsort.c
  src/fwrite.c
  src/gsumm.c
  src/openmp-utils.c
  src/reorder.c
  src/utils.c
Labels: translation

#6536 Missed/partial translations in setops/fread
  R/devel.R
  R/fread.R
  R/setops.R
Labels: translation

#6545 Bumped performance-tests GHA to v1.3.1
  .github/workflows/performance-tests.yml
Labels: ci

#6550 Bump major.minor versions for devel/release/oldrel on GLCI
  .gitlab-ci.yml
Labels: ci

#6549 Always set _R_CHECK_TESTS_NLINES_=0
  .gitlab-ci.yml
Labels: ci

#6553 Run more GHA on pull requests targeting any branch
  .github/workflows/code-quality.yaml
  .github/workflows/performance-tests.yml
  .github/workflows/rchk.yaml
  .github/workflows/test-coverage.yaml
Labels: ci
