Repository Rdatatable/data.table, pull requests merged in 2024-12, with the labels that each got.

#6497 On mac, easier install of data.table with OpenMP
  R/onAttach.R
Labels: openmp

#6654 Version-guard STRING_PTR definition
  src/data.table.h
Labels: internals

#6688 Various tweaks to joins vignette
  vignettes/datatable-joins.Rmd
Labels: documentation

#6647 Remove traces of abandoned plan to change logical01 default
  R/fwrite.R
  man/fread.Rd
  man/fwrite.Rd
Labels: documentation
