Repository Rdatatable/data.table, pull requests merged in 2024-08, with the labels that each got.

#6338 lighten name check for lin-ancient
  .ci/publish.R
Labels: ci

#6345 Add a linter for calls to omp_set_num_threads
  .ci/linters/c/omp_set_num_threads_linter.R
  .dev/CRAN_Release.cmd
  .github/workflows/code-quality.yaml
Labels: ci

#6263 Create rchk GHA
  .github/workflows/rchk.yaml
Labels: ci

#6357 Supply '%s' to translation
  po/R-zh_CN.po
Labels: translation

#6358 Add a code-quality check for translations
  .github/workflows/code-quality.yaml
Labels: ci, translation

#6342 Add a job for linting md files
  .ci/linters/md/news_linter.R
  .github/workflows/code-quality.yaml
  NEWS.md
Labels: ci

#6355 Spanish translations
  .dev/CRAN_Release.cmd
  NEWS.md
  po/R-es.po
  po/es.po
Labels: translation

#6376 Missing lines in config
  .github/workflows/code-quality.yaml
Labels: ci

#6377 3.1.0 --> 3.3.0 in CRAN_release notes
  .dev/CRAN_Release.cmd
Labels: release

#6368 add translation teams to CODEOWNERS
  CODEOWNERS
Labels: translation

#6385 Another round of attempted fixes for R-CMD-check-occasional
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#6379 Fix new_linter & config so that it actually runs, and apply the changes
  .ci/linters/md/news_linter.R
  .github/workflows/code-quality.yaml
  NEWS.0.md
  NEWS.1.md
  NEWS.md
Labels: ci

#6362 remove check for unavailabe dependencies on ancient R
  .gitlab-ci.yml
Labels: ci

#6387 More fixes for occasional CI and older versions of R
  .github/workflows/R-CMD-check-occasional.yaml
  R/test.data.table.R
  R/utils.R
  inst/tests/S4.Rraw
Labels: ci

#6390 More R-CMD-check-occasional fixes
  .github/workflows/R-CMD-check-occasional.yaml
  inst/tests/other.Rraw
Labels: ci

#4306 INTERNAL_ERROR, INTERNAL_STOP macro for internal stops
  R/IDateTime.R
  R/data.table.R
  R/fcast.R
  R/setkey.R
  R/setops.R
  R/utils.R
  inst/tests/tests.Rraw
  src/assign.c
  src/between.c
  src/bmerge.c
  src/chmatch.c
  src/coalesce.c
  src/data.table.h
  src/dogroups.c
  src/fastmean.c
  src/fmelt.c
  src/forder.c
  src/frank.c
  src/fread.c
  src/freadR.c
  src/freadR.h
  src/frollR.c
  src/fsort.c
  src/fwrite.c
  src/fwrite.h
  src/fwriteR.c
  src/gsumm.c
  src/idatetime.c
  src/ijoin.c
  src/nafill.c
  src/openmp-utils.c
  src/rbindlist.c
  src/reorder.c
  src/shift.c
  src/subset.c
  src/types.c
  src/uniqlist.c
  src/utils.c
Labels: internals, translation

#6424 Remove "internal error" translations
  po/R-data.table.pot
  po/R-es.po
  po/R-pt_BR.po
  po/R-zh_CN.po
  po/data.table.pot
  po/es.po
  po/pt_BR.po
  po/zh_CN.po
Labels: translation

#6414 Add compiled translations
  NEWS.md
  inst/po/es/LC_MESSAGES/R-data.table.mo
  inst/po/es/LC_MESSAGES/data.table.mo
  inst/po/pt_BR/LC_MESSAGES/R-data.table.mo
  inst/po/pt_BR/LC_MESSAGES/data.table.mo
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
Labels: translation

#6426 Reorganize .po linters for extensibility, similarity to other checks
  .ci/linters/po/incomplete_translation_linter.R
  .ci/linters/po/tools_check_linter.R
  .ci/linters/po/utf8_linter.R
  .github/workflows/code-quality.yaml
Labels: graphite-ready

#6427 Skip checking .po file if it's not edited on the current branch
  .github/workflows/code-quality.yaml
Labels: graphite-ready

#6415 Add a GHA to prevent backsliding on translation compilation
  .ci/linters/po/incomplete_translation_linter.R
  .ci/linters/po/msgfmt_linter.R
Labels: translation, graphite-ready
