Repository Rdatatable/data.table, pull requests merged in 2024-01, with the labels that each got.

#5876 Remove 'fuzzy' marking from updated translations
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#5877 Mark missed translations
  po/R-zh_CN.po
Labels: translation

#5878 Fix mismatch of messages found by checkPoFiles()
  .dev/CRAN_Release.cmd
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#5879 Compile translations
  .dev/CRAN_Release.cmd
  inst/po/zh_CN/LC_MESSAGES/R-data.table.mo
  inst/po/zh_CN/LC_MESSAGES/data.table.mo
  po/R-zh_CN.po
  po/zh_CN.po
Labels: translation

#4250 Improved handling of list columns with NULL entries
  NEWS.md
  R/print.data.table.R
  inst/tests/tests.Rraw
  man/rbindlist.Rd
Labels: documentation, rbindlist

#5889 frollmax1: frollmax, frollmax adaptive, left adaptive support
  NAMESPACE
  NEWS.md
  R/froll.R
  inst/tests/froll.Rraw
  man/froll.Rd
  src/data.table.h
  src/froll.c
  src/frollR.c
  src/frolladaptive.c
Labels: froll
