Repository Rdatatable/data.table, pull requests merged in 2024-05, with the labels that each got.

#6118 Multiple observed warnings combined in display
  R/test.data.table.R
Labels: tests

#6122 Disable covr (temporarily)
  .github/workflows/test-coverage.yaml
Labels: ci

#6132 Update cron date
  .github/workflows/R-CMD-check-occasional.yaml
Labels: ci

#5474 fread read compressed .bgz
  NEWS.md
  R/fread.R
  inst/tests/ch11b.dat.bgz
  inst/tests/tests.Rraw
Labels: fread
