Repository Rdatatable/data.table, pull requests merged in 2025-01, with the labels that each got.

#6703 setDT() works on S4 slots (again), and := works in under-allocated S4 slots
  NEWS.md
  R/data.table.R
  inst/tests/S4.Rraw
  src/data.table.h
  src/init.c
  src/wrappers.c
Labels: non-atomic column

#6710 Add a devcontainer on alpine
  .devcontainer/r-devel-alpine/Dockerfile
  .devcontainer/r-devel-alpine/devcontainer.json
  configure
  inst/tests/tests.Rraw
Labels: ci

#6727 Adapt to changed RHOME in runner for pkgup GHA job
  .github/workflows/pkgup.yaml
Labels: ci

#6749 Request any changes to GOVERNANCE tag all committers
  CODEOWNERS
  GOVERNANCE.md
Labels: governance

#6760 don't check malloc(0)
  .ci/linters/c/alloc_linter.R
Labels: ci

#6762 Activate implicit_integer_linter
  .ci/.lintr.R
  .dev/CRAN_Release.cmd
  R/IDateTime.R
  R/between.R
  R/data.table.R
  R/fdroplevels.R
  R/fmelt.R
  R/foverlaps.R
  R/fread.R
  R/fwrite.R
  R/groupingsets.R
  R/onLoad.R
  R/openmp-utils.R
  R/print.data.table.R
  R/setkey.R
  R/setops.R
  R/tables.R
  R/test.data.table.R
  R/translation.R
  R/utils.R
  R/wrappers.R
Labels: ci

#6743 Mention possible limitations of strtrim approach
  NEWS.md
  man/print.data.table.Rd
Labels: documentation

#6719 Update Brazilian Portuguese translation
  po/R-pt_BR.po
  po/pt_BR.po
Labels: translation

#6748 Clarify proper nouns for role names
  GOVERNANCE.md
Labels: governance

#6778 remove carriage return from translation
  po/data.table.pot
  src/dogroups.c
Labels: translation

#6780 fix missing ")" in message
  po/data.table.pot
  src/assign.c
Labels: translation

#6516 Russian translation
  CODEOWNERS
  inst/po/ru/LC_MESSAGES/R-data.table.mo
  inst/po/ru/LC_MESSAGES/data.table.mo
  po/R-ru.po
  po/ru.po
  vignettes/ru/datatable-importing.Rmd
  vignettes/ru/datatable-intro.Rmd
  vignettes/ru/datatable-reshape.Rmd
Labels: translation
