Repository Rdatatable/data.table, pull requests merged in 2025-03, with the labels that each got.

#6618 Automate lang links
  vignettes/_translation_links.R
  vignettes/datatable-benchmarking.Rmd
  vignettes/datatable-faq.Rmd
  vignettes/datatable-importing.Rmd
  vignettes/datatable-intro.Rmd
  vignettes/datatable-joins.Rmd
  vignettes/datatable-keys-fast-subset.Rmd
  vignettes/datatable-programming.Rmd
  vignettes/datatable-reference-semantics.Rmd
  vignettes/datatable-reshape.Rmd
  vignettes/datatable-sd-usage.Rmd
  vignettes/datatable-secondary-indices-and-auto-indexing.Rmd
  vignettes/fr/datatable-benchmarking.Rmd
  vignettes/fr/datatable-faq.Rmd
  vignettes/fr/datatable-importing.Rmd
  vignettes/fr/datatable-intro.Rmd
  vignettes/fr/datatable-keys-fast-subset.Rmd
  vignettes/fr/datatable-programming.Rmd
  vignettes/fr/datatable-reference-semantics.Rmd
  vignettes/fr/datatable-reshape.Rmd
  vignettes/fr/datatable-sd-usage.Rmd
  vignettes/fr/datatable-secondary-indices-and-auto-indexing.Rmd
  vignettes/ru/datatable-importing.Rmd
  vignettes/ru/datatable-intro.Rmd
  vignettes/ru/datatable-reshape.Rmd
Labels: translation

#6826 Add a mask for future %||%, use it
  R/IDateTime.R
  R/between.R
  R/data.table.R
  R/foverlaps.R
  R/print.data.table.R
  R/utils.R
  man/foverlaps.Rd
Labels: code-quality

#6746 GitLab CI workflow with sanitizers
  .dev/lsan.supp
  .gitlab-ci.yml
Labels: ci

#6633 Make sure data.table is linked (not just compiled) with `-fopenmp` in this particular branch of `configure` for Darwin
  configure
Labels: openmp
