Repository Rdatatable/data.table, pull requests merged in 2025-07, with the labels that each got.

#6435 [cbindlist/mergelist] Implement cbindlist
  NAMESPACE
  R/mergelist.R
  inst/tests/mergelist.Rraw
  inst/tests/tests.Rraw
  man/cbindlist.Rd
  src/data.table.h
  src/init.c
  src/mergelist.c
  tests/mergelist.R
Labels: graphite-ready

#6437 [cbindlist/mergelist] mergepair workhorse
  R/data.table.R
  R/mergelist.R
  R/onLoad.R
  inst/tests/mergelist.Rraw
Labels: graphite-ready

#6438 [cbindlist/mergelist] copyCols
  src/data.table.h
  src/init.c
  src/mergelist.c
Labels: graphite-ready

#6519 Adding translation team logos
  .graphics/translation-team-codelogos/datatable_es.png
  .graphics/translation-team-codelogos/datatable_es.svg
  .graphics/translation-team-codelogos/datatable_fr.png
  .graphics/translation-team-codelogos/datatable_fr.svg
  .graphics/translation-team-codelogos/datatable_hi.png
  .graphics/translation-team-codelogos/datatable_hi.svg
  .graphics/translation-team-codelogos/datatable_pt.png
  .graphics/translation-team-codelogos/datatable_pt.svg
  .graphics/translation-team-codelogos/datatable_ru.png
  .graphics/translation-team-codelogos/datatable_ru.svg
  .graphics/translation-team-codelogos/datatable_zh.png
  .graphics/translation-team-codelogos/datatable_zh.svg
  .graphics/translation-team-logos/datatable-es.png
  .graphics/translation-team-logos/datatable-fr.png
  .graphics/translation-team-logos/datatable-hi.png
  .graphics/translation-team-logos/datatable-pt.png
  .graphics/translation-team-logos/datatable-ru.png
  .graphics/translation-team-logos/datatable-zh.png
  .graphics/translation-team-logos/rdatatable-es.svg
  .graphics/translation-team-logos/rdatatable-fr.svg
  .graphics/translation-team-logos/rdatatable-hi.svg
  .graphics/translation-team-logos/rdatatable-pt.svg
  .graphics/translation-team-logos/rdatatable-ru.svg
  .graphics/translation-team-logos/rdatatable-zh.svg
  CODEOWNERS
Labels: translation

#7151 add french version of datatable-joins.Rmd
  vignettes/datatable-joins.Rmd
  vignettes/fr/datatable-joins.Rmd
Labels: translation

#7214 Use a less generic name than 'init' for routine to initialize Inf & NaN
  src/fread.c
Labels: code-quality
